Name: DefaultConfig
BaseConfig:
Format: YAML
Configuration:
  ConnectionStrings:
    DefaultConnection: default DB connection string
    SpecialConnection: default config for special DB connection string
  Logging:
    Level: Information