Name: JsonConfiguredClient
BaseConfig: ../DefaultConfig
Format: JSON
Configuration: |
  {
      "Logging": "Warning",
      "ConnectionStrings": {
          "DefaultConnection": "taken from JSON config",
          "SpecialConnection": "taken from JSON config"
      }
  }